#!perl -w
use strict;
use warnings FATAL => 'all';
print "the input file is plink.lmiss and plink.frq generated by plink, the only parameter if the minor allele number.\n";
print "the allele with count smaller than the specific number would be excluded\n";
my $man = $ARGV[0];

my %avaliableNumber;
open INPUT, "plink.lmiss";
my $linenumber=0;
while( my $line=<INPUT> ){
	if( $line=~/(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/ && $linenumber >0){
		my $number=$4-$3;
		$avaliableNumber{$2}=$number;
	}
	$linenumber++;
}
close INPUT;

$linenumber=0;
open OUTPUT, ">excludeSnps";
open INPUT, "plink.frq";
while( my $line=<INPUT> ){
	if( $line=~/(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/ && $linenumber>0){
		if( $avaliableNumber{$2}*$5 <$man ){
			print OUTPUT "$2\n";
		}
	}
	$linenumber++;
}
close INPUT;
close OUTPUT;

